"""Audit intersection between complaint trace tokens and serialized_events tokens.

Purpose:
- For a complaint product_id set, compute trace tokens generated by resolve-input.
- Compute token universe available in serialized_events artifact.
- Find intersection and propose a test subset with expected non-zero hits.

Usage (PowerShell example):
  cd form-analysis-server/backend
  python -m scripts.manual.audit_artifact_token_intersection ^
    --base-url http://localhost:18102 ^
    --tenant-code demo ^
    --username demo_manager ^
    --password DemoManager123! ^
    --artifact-file "C:/Users/yucheng/Desktop/september_v2/ut_serialized_results.json" ^
    --product-ids "id1,id2,id3"
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any
from urllib import parse, request


def _split_ids(raw: str) -> list[str]:
    parts = [x.strip() for x in raw.replace(";", ",").replace("\n", ",").split(",")]
    out: list[str] = []
    seen: set[str] = set()
    for p in parts:
        if not p:
            continue
        k = p.lower()
        if k in seen:
            continue
        seen.add(k)
        out.append(p)
    return out


def _load_ids_from_file(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    return _split_ids(text)


def _extract_serialized_tokens(artifact_file: Path) -> set[str]:
    data = json.loads(artifact_file.read_text(encoding="utf-8"))
    out: set[str] = set()
    if not isinstance(data, list):
        return out
    for item in data:
        if not isinstance(item, dict):
            continue
        event_id = str(item.get("event_id") or item.get("id") or "").strip()
        if event_id:
            out.add(event_id)
        ctx = item.get("context") if isinstance(item.get("context"), dict) else {}
        produce_no = str(
            ctx.get("Produce_No.")
            or ctx.get("produce_no")
            or ctx.get("LOT NO.")
            or ctx.get("lot_no")
            or ""
        ).strip()
        if produce_no:
            out.add(produce_no)
    return out


def _login(base_url: str, tenant_code: str, username: str, password: str) -> dict[str, Any]:
    payload = json.dumps(
        {"tenant_code": tenant_code, "username": username, "password": password}
    ).encode("utf-8")
    req = request.Request(
        f"{base_url.rstrip('/')}/api/auth/login",
        data=payload,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    if not isinstance(data, dict) or not data.get("api_key") or not data.get("tenant_id"):
        raise RuntimeError("login response missing api_key/tenant_id")
    return data


def _resolve_input(
    base_url: str,
    tenant_id: str,
    api_key: str,
    product_ids: list[str],
) -> dict[str, Any]:
    query = parse.urlencode({"product_ids": ",".join(product_ids)})
    req = request.Request(
        f"{base_url.rstrip('/')}/api/v2/analytics/artifacts/serialized_events/resolve-input?{query}",
        method="GET",
        headers={"X-Tenant-Id": tenant_id, "X-API-Key": api_key},
    )
    with request.urlopen(req, timeout=60) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    if not isinstance(data, dict):
        raise RuntimeError("resolve-input response is not an object")
    return data


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--tenant-code", required=True)
    parser.add_argument("--username", required=True)
    parser.add_argument("--password", required=True)
    parser.add_argument("--artifact-file", required=True)
    parser.add_argument("--product-ids", default="")
    parser.add_argument("--ids-file", default="")
    parser.add_argument("--output-json", default="")
    args = parser.parse_args()

    product_ids: list[str] = []
    if args.product_ids:
        product_ids.extend(_split_ids(args.product_ids))
    if args.ids_file:
        product_ids.extend(_load_ids_from_file(Path(args.ids_file)))
        product_ids = _split_ids(",".join(product_ids))
    if not product_ids:
        raise RuntimeError("no product_ids provided")

    artifact_tokens = _extract_serialized_tokens(Path(args.artifact_file))
    auth = _login(args.base_url, args.tenant_code, args.username, args.password)
    tenant_id = str(auth["tenant_id"])
    api_key = str(auth["api_key"])

    baseline = _resolve_input(args.base_url, tenant_id, api_key, product_ids)

    trace_tokens_map = baseline.get("trace_tokens") if isinstance(baseline.get("trace_tokens"), dict) else {}
    matches_map = baseline.get("matches") if isinstance(baseline.get("matches"), dict) else {}
    pid_to_intersection: dict[str, list[str]] = {}
    recommended_ids: list[str] = []
    guaranteed_by_matches: list[str] = []
    for pid in product_ids:
        tokens = [str(x).strip() for x in trace_tokens_map.get(pid, []) if str(x).strip()]
        match_tokens = [str(x).strip() for x in matches_map.get(pid, []) if str(x).strip()]
        inter = sorted({t for t in tokens if t in artifact_tokens})
        pid_to_intersection[pid] = inter
        if inter:
            recommended_ids.append(pid)
        if match_tokens:
            guaranteed_by_matches.append(pid)

    rerun_intersection = None
    if recommended_ids:
        rerun_intersection = _resolve_input(args.base_url, tenant_id, api_key, recommended_ids)
    rerun_guaranteed = None
    if guaranteed_by_matches:
        rerun_guaranteed = _resolve_input(args.base_url, tenant_id, api_key, guaranteed_by_matches)

    result = {
        "input_count": len(product_ids),
        "artifact_token_count": len(artifact_tokens),
        "baseline_summary": {
            "requested_count": baseline.get("requested_count"),
            "resolved_count": baseline.get("resolved_count"),
            "unmatched_count": baseline.get("unmatched_count"),
            "trace_attempted_count": baseline.get("trace_attempted_count"),
            "trace_resolved_count": baseline.get("trace_resolved_count"),
        },
        "recommended_count": len(recommended_ids),
        "recommended_product_ids_by_trace_intersection": recommended_ids,
        "guaranteed_count_by_matches": len(guaranteed_by_matches),
        "guaranteed_product_ids_by_matches": guaranteed_by_matches,
        "pid_to_trace_token_intersection": pid_to_intersection,
        "rerun_summary_by_trace_intersection": None
        if not isinstance(rerun_intersection, dict)
        else {
            "requested_count": rerun_intersection.get("requested_count"),
            "resolved_count": rerun_intersection.get("resolved_count"),
            "unmatched_count": rerun_intersection.get("unmatched_count"),
            "trace_attempted_count": rerun_intersection.get("trace_attempted_count"),
            "trace_resolved_count": rerun_intersection.get("trace_resolved_count"),
        },
        "rerun_summary_by_guaranteed_matches": None
        if not isinstance(rerun_guaranteed, dict)
        else {
            "requested_count": rerun_guaranteed.get("requested_count"),
            "resolved_count": rerun_guaranteed.get("resolved_count"),
            "unmatched_count": rerun_guaranteed.get("unmatched_count"),
            "trace_attempted_count": rerun_guaranteed.get("trace_attempted_count"),
            "trace_resolved_count": rerun_guaranteed.get("trace_resolved_count"),
        },
    }

    print(json.dumps(result, ensure_ascii=False, indent=2))
    if args.output_json:
        out_path = Path(args.output_json)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
