"""Artifact routes for analytics API."""

import logging
import time
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_tenant
from app.core.database import get_db
from app.models.core.tenant import Tenant

from .helpers import (
    _classify_unmatched_reason,
    _extract_trace_tokens,
    _resolve_trace_tokens_from_db,
    check_rate_limit,
)
from .schemas import (
    ArtifactInputResolveResponse,
    ArtifactListItem,
    ArtifactUnifiedSnapshotResponse,
)

logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("/artifacts", response_model=list[ArtifactListItem])
async def list_artifacts(request: Request = None):
    """List available pre-generated analytics artifacts (JSON files).

    These artifacts are generated by the Analytical-Four pipeline and mounted into the backend container.
    The backend only serves allowlisted filenames to avoid path traversal/leaks.
    """

    if request:
        check_rate_limit(request, endpoint="/api/v2/analytics/artifacts")

    from app.services.analytics_external import list_analytics_artifacts

    items = list_analytics_artifacts()
    return [
        ArtifactListItem(
            key=i.key,
            filename=i.filename,
            exists=i.exists,
            size_bytes=i.size_bytes,
            mtime_epoch=i.mtime_epoch,
        )
        for i in items
    ]


@router.get("/artifacts/{artifact_key}")
async def get_artifact(artifact_key: str, request: Request = None) -> Any:
    """Fetch one allowlisted analytics artifact.

    NOTE: This endpoint is kept for backwards compatibility.
    The frontend should prefer the list/detail endpoints which only return table/chart data.
    """

    if request:
        check_rate_limit(request, endpoint="/api/v2/analytics/artifacts/{artifact_key}")

    try:
        from app.services.analytics_external import get_analytics_artifact_list_view, parse_artifact_key

        key = parse_artifact_key(artifact_key)
        return get_analytics_artifact_list_view(key)
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=(
                "Analytics artifact not found. "
                "Please generate it with Analytical-Four and place it under SEPTEMBER_V2_PATH (or set ANALYTICS_ARTIFACTS_DIR)."
            ),
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Unknown analytics artifact key")
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to load analytics artifact")


@router.get("/artifacts/{artifact_key}/list")
async def get_artifact_list(
    artifact_key: str,
    product_ids: str | None = None,
    request: Request = None,
) -> Any:
    """Get compact list view for an artifact.

    Returns only the fields needed to render tables/charts.
    """

    if request:
        check_rate_limit(request, endpoint="/api/v2/analytics/artifacts/{artifact_key}/list")

    try:
        from app.services.analytics_external import get_analytics_artifact_list_view, parse_artifact_key, _split_product_ids

        key = parse_artifact_key(artifact_key)
        pids = _split_product_ids(product_ids)
        return get_analytics_artifact_list_view(key, product_ids=pids)
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=(
                "Analytics artifact not found. "
                "Please generate it with Analytical-Four and place it under SEPTEMBER_V2_PATH (or set ANALYTICS_ARTIFACTS_DIR)."
            ),
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Unknown analytics artifact key")
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to load analytics artifact")


@router.get(
    "/artifacts/{artifact_key}/resolve-input",
    response_model=ArtifactInputResolveResponse,
)
async def resolve_artifact_input(
    artifact_key: str,
    product_ids: str | None = None,
    request: Request = None,
    session: AsyncSession = Depends(get_db),
    current_tenant: Tenant = Depends(get_current_tenant),
) -> ArtifactInputResolveResponse:
    """Resolve user inputs into artifact-effective filter tokens."""
    t0 = time.perf_counter()

    if request:
        check_rate_limit(request, endpoint="/api/v2/analytics/artifacts/{artifact_key}/resolve-input")

    try:
        from app.services.analytics_external import (
            _split_product_ids,
            parse_artifact_key,
            resolve_artifact_product_inputs,
        )

        key = parse_artifact_key(artifact_key)
        pids = _split_product_ids(product_ids)
        base = resolve_artifact_product_inputs(key, product_ids=pids)
        base_normalized = (
            base.get("normalized_inputs", {})
            if isinstance(base.get("normalized_inputs", {}), dict)
            else {}
        )

        trace_tokens: dict[str, list[str]] = {}
        trace_token_source: dict[str, str] = {}
        unresolved = [x for x in base.get("unmatched", []) if isinstance(x, str)]
        trace_attempted_count = len(unresolved)
        db_trace_tokens = await _resolve_trace_tokens_from_db(
            session=session,
            tenant_id=current_tenant.id,
            requested_ids=unresolved,
            normalized_inputs=base_normalized,
        )
        if unresolved:
            from app.api.traceability import trace_by_product_id

            for pid in unresolved:
                if db_trace_tokens.get(pid):
                    trace_tokens[pid] = list(db_trace_tokens.get(pid, []))
                    trace_token_source[pid] = "db_trace_lot"
                    continue
                try:
                    trace_payload = await trace_by_product_id(
                        product_id=pid,
                        db=session,
                        current_tenant=current_tenant,
                    )
                    tokens = _extract_trace_tokens(trace_payload)
                    if tokens:
                        trace_tokens[pid] = tokens
                        trace_token_source[pid] = "traceability"
                except HTTPException:
                    trace_tokens[pid] = []
                except Exception:
                    trace_tokens[pid] = []

        if not trace_tokens:
            artifact_row_count = int(base.get("artifact_row_count") or 0)
            base_normalized = (
                base_normalized
            )
            base_diag = (
                base.get("match_diagnostics", {})
                if isinstance(base.get("match_diagnostics", {}), dict)
                else {}
            )
            base_unmatched = (
                base.get("unmatched", [])
                if isinstance(base.get("unmatched", []), list)
                else []
            )
            enriched_diag: dict[str, dict[str, Any]] = {}
            for pid in pids:
                pid_base_diag = base_diag.get(pid) if isinstance(base_diag.get(pid), dict) else {}
                reason_code = ""
                reason_message = ""
                if pid in base_unmatched:
                    reason_code, reason_message = _classify_unmatched_reason(
                        requested_id=pid,
                        trace_candidates=[],
                        artifact_row_count=artifact_row_count,
                    )
                enriched_diag[pid] = {
                    "candidate_count": int(pid_base_diag.get("candidate_count") or len(base_normalized.get(pid, []))),
                    "matched_by": pid_base_diag.get("matched_by", []) if isinstance(pid_base_diag.get("matched_by", []), list) else [],
                    "reason_code": reason_code,
                    "reason_message": reason_message,
                    "trace_source": trace_token_source.get(pid, ""),
                }

            resolved_list = [
                str(x).strip()
                for x in (
                    base.get("resolved", [])
                    if isinstance(base.get("resolved", []), list)
                    else []
                )
                if str(x).strip()
            ]
            unmatched_list = [str(x).strip() for x in base_unmatched if str(x).strip()]
            reason_counts: dict[str, int] = {}
            for pid in unmatched_list:
                code = str((enriched_diag.get(pid) or {}).get("reason_code") or "").strip()
                if not code:
                    continue
                reason_counts[code] = int(reason_counts.get(code, 0)) + 1

            return ArtifactInputResolveResponse(
                requested=pids,
                requested_count=len(pids),
                normalized_inputs={pid: list(base_normalized.get(pid, [])) for pid in pids},
                resolved=resolved_list,
                resolved_count=len(resolved_list),
                unmatched=unmatched_list,
                unmatched_count=len(unmatched_list),
                matches={
                    pid: [str(x).strip() for x in ((base.get("matches", {}) or {}).get(pid, []) if isinstance((base.get("matches", {}) or {}).get(pid, []), list) else []) if str(x).strip()][:20]
                    for pid in pids
                },
                match_diagnostics=enriched_diag,
                trace_tokens={},
                trace_attempted_count=trace_attempted_count,
                trace_resolved_count=0,
                unmatched_reason_counts=reason_counts,
                elapsed_ms=round((time.perf_counter() - t0) * 1000, 2),
            )

        # Re-run matching by using trace-derived candidates and map hits back to requested IDs.
        token_order: list[str] = []
        token_seen: set[str] = set()
        for pid in unresolved:
            for tok in trace_tokens.get(pid, []):
                tk = tok.lower()
                if tk in token_seen:
                    continue
                token_seen.add(tk)
                token_order.append(tok)

        token_result = (
            resolve_artifact_product_inputs(key, product_ids=token_order)
            if token_order
            else {"matches": {}, "resolved": []}
        )
        token_matches = token_result.get("matches", {}) if isinstance(token_result, dict) else {}
        artifact_row_count = int(base.get("artifact_row_count") or 0)
        base_normalized = (
            base_normalized
        )
        base_diag = (
            base.get("match_diagnostics", {})
            if isinstance(base.get("match_diagnostics", {}), dict)
            else {}
        )

        merged_matches: dict[str, list[str]] = {}
        merged_resolved: list[str] = []
        merged_resolved_seen: set[str] = set()
        for x in base.get("resolved", []):
            s = str(x).strip()
            if not s:
                continue
            k = s.lower()
            if k in merged_resolved_seen:
                continue
            merged_resolved_seen.add(k)
            merged_resolved.append(s)

        base_matches = base.get("matches", {}) if isinstance(base.get("matches", {}), dict) else {}
        for pid in pids:
            direct = base_matches.get(pid, []) if isinstance(base_matches, dict) else []
            hits: list[str] = []
            hit_seen: set[str] = set()
            for h in direct:
                hs = str(h).strip()
                if not hs:
                    continue
                hk = hs.lower()
                if hk in hit_seen:
                    continue
                hit_seen.add(hk)
                hits.append(hs)
            if not hits:
                for tok in trace_tokens.get(pid, []):
                    for h in token_matches.get(tok, []):
                        hs = str(h).strip()
                        if not hs:
                            continue
                        hk = hs.lower()
                        if hk in hit_seen:
                            continue
                        hit_seen.add(hk)
                        hits.append(hs)
            for h in hits:
                hk = h.lower()
                if hk not in merged_resolved_seen:
                    merged_resolved_seen.add(hk)
                    merged_resolved.append(h)
            merged_matches[pid] = hits[:20]

        merged_unmatched = [pid for pid in pids if not merged_matches.get(pid)]
        merged_diag: dict[str, dict[str, Any]] = {}
        for pid in pids:
            pid_base_diag = base_diag.get(pid) if isinstance(base_diag.get(pid), dict) else {}
            matched_by_raw = pid_base_diag.get("matched_by", [])
            matched_by = [str(x).strip() for x in matched_by_raw if str(x).strip()] if isinstance(matched_by_raw, list) else []
            if not matched_by and merged_matches.get(pid):
                # Fallback path: direct match was empty, but trace token mapping resolved hits.
                matched_by = trace_tokens.get(pid, [])[:20]
            reason_code = ""
            reason_message = ""
            if pid in merged_unmatched:
                reason_code, reason_message = _classify_unmatched_reason(
                    requested_id=pid,
                    trace_candidates=trace_tokens.get(pid, []),
                    artifact_row_count=artifact_row_count,
                )
            merged_diag[pid] = {
                "candidate_count": int(pid_base_diag.get("candidate_count") or len(base_normalized.get(pid, []))),
                "matched_by": matched_by[:20],
                "reason_code": reason_code,
                "reason_message": reason_message,
                "trace_source": trace_token_source.get(pid, ""),
            }

        trace_resolved_count = 0
        for pid in unresolved:
            if merged_matches.get(pid):
                trace_resolved_count += 1

        reason_counts: dict[str, int] = {}
        for pid in merged_unmatched:
            code = str((merged_diag.get(pid) or {}).get("reason_code") or "").strip()
            if not code:
                continue
            reason_counts[code] = int(reason_counts.get(code, 0)) + 1

        return ArtifactInputResolveResponse(
            requested=pids,
            requested_count=len(pids),
            normalized_inputs={pid: list(base_normalized.get(pid, [])) for pid in pids},
            resolved=merged_resolved[:100],
            resolved_count=len(merged_resolved[:100]),
            unmatched=merged_unmatched,
            unmatched_count=len(merged_unmatched),
            matches=merged_matches,
            match_diagnostics=merged_diag,
            trace_tokens=trace_tokens,
            trace_attempted_count=trace_attempted_count,
            trace_resolved_count=trace_resolved_count,
            unmatched_reason_counts=reason_counts,
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 2),
        )
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=(
                "Analytics artifact not found. "
                "Please generate it with Analytical-Four and place it under SEPTEMBER_V2_PATH (or set ANALYTICS_ARTIFACTS_DIR)."
            ),
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Unknown analytics artifact key")
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to resolve analytics artifact input")


@router.get(
    "/artifacts/{artifact_key}/snapshot",
    response_model=ArtifactUnifiedSnapshotResponse,
)
async def get_artifact_unified_snapshot(
    artifact_key: str,
    product_ids: str | None = None,
    request: Request = None,
) -> ArtifactUnifiedSnapshotResponse:
    """Get a unified aggregate snapshot for cross-view rendering."""

    if request:
        check_rate_limit(request, endpoint="/api/v2/analytics/artifacts/{artifact_key}/snapshot")

    try:
        from app.services.analytics_external import (
            _split_product_ids,
            get_analytics_artifact_unified_snapshot,
            parse_artifact_key,
        )

        key = parse_artifact_key(artifact_key)
        pids = _split_product_ids(product_ids)
        data = get_analytics_artifact_unified_snapshot(key, product_ids=pids)
        return ArtifactUnifiedSnapshotResponse(**data)
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=(
                "Analytics artifact not found. "
                "Please generate it with Analytical-Four and place it under SEPTEMBER_V2_PATH (or set ANALYTICS_ARTIFACTS_DIR)."
            ),
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Unknown analytics artifact key")
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to build analytics unified snapshot")


@router.get("/artifacts/{artifact_key}/detail/{item_id}")
async def get_artifact_detail(
    artifact_key: str,
    item_id: str,
    request: Request = None,
) -> Any:
    """Get compact detail view for a single item.

    Returns only the fields needed to render tables/charts.
    """

    if request:
        check_rate_limit(request, endpoint="/api/v2/analytics/artifacts/{artifact_key}/detail/{item_id}")

    try:
        from app.services.analytics_external import get_analytics_artifact_detail_view, parse_artifact_key

        key = parse_artifact_key(artifact_key)
        return get_analytics_artifact_detail_view(key, item_id)
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=(
                "Analytics artifact not found. "
                "Please generate it with Analytical-Four and place it under SEPTEMBER_V2_PATH (or set ANALYTICS_ARTIFACTS_DIR)."
            ),
        )
    except KeyError as e:
        msg = str(e)
        if "not found" in msg.lower():
            raise HTTPException(status_code=404, detail="Artifact item not found")
        raise HTTPException(status_code=404, detail="Unknown analytics artifact key")
    except Exception:
        raise HTTPException(status_code=500, detail="Failed to load analytics artifact")
